name: Build and Deploy WASM

on:
  push:
    branches: [master]
    # Optional: Only trigger on changes to vault_crypto
    # paths:
    #   - 'vault_crypto/**'
    #   - '.github/workflows/build-and-deploy-wasm.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the current repository (the whole workspace)
      - name: Checkout vault workspace
        uses: actions/checkout@v4

      # Setup Rust
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      # Install wasm-pack
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      # Build WASM from the workspace
      - name: Build WASM
        run: |
          # Navigate to vault_crypto within the workspace
          cd vault_crypto

          # Build with wasm-pack
          wasm-pack build --target web --out-dir pkg --release

          # Show what was built
          echo "Built files:"
          ls -la pkg/

      # Checkout the vault-web repository
      - name: Checkout vault-web
        uses: actions/checkout@v4
        with:
          repository: antonio-leitao/vault-web
          token: ${{ secrets.VAULT_DEPLOY_TOKEN }}
          path: vault-web
          ref: main # or master, depending on your default branch

      # Copy built files to vault-web
      - name: Copy WASM files
        run: |
          # Create pkg directory if it doesn't exist
          mkdir -p vault-web/pkg

          # Copy all built files from vault_crypto/pkg to vault-web/pkg
          cp -r vault_crypto/pkg/* vault-web/pkg/

          # List copied files for verification
          echo "Copied files:"
          ls -la vault-web/pkg/

      # Commit and push to vault-web
      - name: Commit and push
        run: |
          cd vault-web
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Check if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update WASM build from vault@${{ github.sha }}"
            git push
            echo "✅ Successfully deployed WASM to vault-web"
          else
            echo "📝 No changes to commit"
          fi
